INSERT INTO users (name, age) VALUES ("Justin", 27);
INSERT INTO users (name, age) VALUES ("Desi", 24);
INSERT INTO users (name, age) VALUES ("Larissa", 20);
INSERT INTO users (name, age) VALUES ("Nick", 29);
INSERT INTO users (name, age) VALUES ("Brittany", 31);
INSERT INTO users (name, age) VALUES ("Eric", 32);
INSERT INTO users (name, age) VALUES ("Alex", 26);
INSERT INTO users (name, age) VALUES ("Ryan", 30);
INSERT INTO users (name, age) VALUES ("Mary Ann", 59);
INSERT INTO users (name, age) VALUES ("Diane", 56);
INSERT INTO users (name, age) VALUES ("Henry", 57);
INSERT INTO users (name, age) VALUES ("Erica", 44);
INSERT INTO users (name, age) VALUES ("Priscilla", 33);
INSERT INTO users (name, age) VALUES ("Briana", 25);
INSERT INTO users (name, age) VALUES ("Amanda", 30);
INSERT INTO users (name, age) VALUES ("Ashley", 24);
INSERT INTO users (name, age) VALUES ("Whitney", 26);
INSERT INTO users (name, age) VALUES ("Suzie", 27);
INSERT INTO users (name, age) VALUES ("Benson", 35);
INSERT INTO users (name, age) VALUES ("Candace", 29);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Start paper company", "business", 5000.00, "10-21-2017", "12-31-2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("End world hunger", "charity", 2000.00, "04-12-2016", "9-13-2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Go to Flatiron School", "education", 1000.00, "7-13-2020", "10-19-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help with medical bills", "charity", 750.00, "12-10-2015", "05-27-2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Produce a rock album", "music", 200.00, "07-25-2018", "12-29-2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Start my dogs modeling business", "business", 300.00, "03-15-2011", "09-25-2011");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Become franchise owner of Chick Fil A", "business", 800.00, "05-07-2014", "08-23-2014");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Buy books for college", "charity", 1500.00, "08-23-2017", "12-15-2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rent venue for concert", "music", 3300.00, "02-03-2016", "03-19-2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Feature Eminem on my new song", "music", 4000.00, "01-01-2013", "09-03-2013");

INSERT INTO pledges (amount, user_id, project_id) VALUES (250.00, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000.00, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600.00, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000.00, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400.00, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (333.00, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.00, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125.00, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (215.00, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140.00, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500.00, 17, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700.00, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350.00, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65.00, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (170.00, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900.00, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (275.00, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27.00, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75.00, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300.00, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.00, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40.00, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (240.00, 10, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30.00, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90.00, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (860.00, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (330.00, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (460.00, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120.00, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500.00, 19, 1);

